### ISSUE TITLE
Set up Guice for injections

### ISSUE THREAD

**Issue by willyim123** [howardjohn/Kitchen-Companion#65]
Set up [Guice](https://github.com/google/guice) so that we can use injections and avoid the use of Singletons and Factories for our DAO (and BLL) classes (once they are implemented). By doing this, we can use the @Inject annotation wherever we need to use the DAO classes and avoid having to instantiate them.

**Comment by howardjohn** [comment]
Can you justify what benefit this actually brings us? I am not sure it's a good idea

**Comment by willyim123** [comment]
This will reduce boilerplate code when we are trying to access the DAOs because we are trying to ensure they are singletons when we access them. Why might this not be a good idea?

**Comment by howardjohn** [comment]
The only place that will use them, as well as like every class we make is the `Server` class. I don't think it will reduce any boilerplate at all - there will be 1 single place where all the dependencies for `Server` are created, and passed in to the constructor. I think adding Guice will just add unnecessary complexity and indirection for no actual benefit. I just think its way overkill for such a simple application and wouldn't actually yield any benefits.

**Comment by willyim123** [comment]
I didn't realize you called the `Provider` classes directly from the Server.  I feel like with this approach, we are cramming too much of the logic into that one class. My thought process for using Guice was decoupling the logic a bit more and creating `BLL` classes that the `Server` would call to retrieve the processed `Recipes`, `Ingredients` and `Comments` after they were retrieved from the `DAO`.

**Comment by howardjohn** [comment]
We could create bll classes, but there is really very very minimal logic. Look at the Server right now. for example with the create recipe, it just takes in a request that has all of the data for a recipe and it will call `DAO.createRecipe(recipe)` for it. There is really no logic in our project for 99% of the stuff we are doing. We can definitely pull these out into separate classes, but I am still not sure what Guice does to help us. Regardless of what form they are in, `Server` has all of the dependencies. Isn't the only benefit of Guice when you have more complex dependencies?

**Comment by willyim123** [comment]
It might not be necessary to add BLL classes (the main reason I wanted to use Guice) because our project does not contain too much logic outside of what we are doing in the DAOs, so I will close this task for the time being.
